name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::devtools
            any::tibble
            any::BiocManager

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install AssignSampleIDs
        run: Rscript -e "devtools::install(repos = BiocManager::repositories())"

      - name: Check AssignSampleIDs
        run: Rscript -e "devtools::check(vignettes = TRUE)"

      - name: Run unit tests
        run: Rscript -e "devtools::test()"
